-- ************************************************************ ********************************
-- Name: Vivian Chiu
-- Date: Friday, August 9th 2019
-- Class: DBS301
-- Topic: John Wick's Real Estate Agency
-- ********************************************************************************************

CREATE TABLE a02AdOutlet (
	adOutletId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	outletType VARCHAR(15), 
	outletName VARCHAR(25), 
	outletContact# INTEGER,
	CONSTRAINT a02AdOutlet_PK PRIMARY KEY(adOutletId)
)
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Website', 'kijiji.com', 18006831991);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Newspaper', 'Toronto Star', 14168694300);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Newspaper', 'Daily Bugle', 18881931555 );
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Magazine', 'Homes Plus', 15193337586);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Magazine', 'Canadian Real Estate', 14163598333);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Website', 'Homes4Cash.com', 18885720591);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Magazine', 'Modern Living', 19052225348);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Newspaper', 'Globe and Mail', 14169403366);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Newspaper', 'The Guardian', 15243005896);
INSERT INTO a02AdOutlet (outletType, outletName, outletContact#) VALUES ('Website', 'HomesHomesHomes', 18009673944);

CREATE TABLE a02Agency (
	agencyId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	agencyName VARCHAR(15), 
	mainPhone# INTEGER, 
	CONSTRAINT a02Agency_PK PRIMARY KEY(agencyId)
)
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('RE/MAX', 14169003975);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Royal Canadian Realty' 14167493033);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Home Life Realty', 15198675555);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Origin Lofts', 15192435768);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Century 21', 12344329867);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Sutton Group Heritage', 12224651324);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Royal LePage', 19051012394);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('HR HOMES', 19052228686);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Killer Homes', 15552394578);
INSERT INTO a02Agency (agencyName, mainPhone#) VALUES ('Safeway Homes', 18002936485);

CREATE TABLE a02Area (
	areaId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	areaName VARCHAR(20),
	generalComments VARCHAR(3000),
	CONSTRAINT a02Area_PK PRIMARY KEY (areaId)
);

INSERT INTO a02Area (areaName, generalComments) VALUES ('Bayview', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('West Hill', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Guildwood', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Port Union', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Rosewood', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Vaughan', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Unionville', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Pickering', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Chinatown', NULL);
INSERT INTO a02Area (areaName, generalComments) VALUES ('Collingwood', NULL);

CREATE TABLE a02PropertyType (
	propertyTypeId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	propertyType VARCHAR(20), 
	CONSTRAINT a02PropertyTypeId_PK PRIMARY KEY (propertyTypeId)
);

INSERT INTO a02PropertyType (propertyType) VALUES ('Townhouse');
INSERT INTO a02PropertyType (propertyType) VALUES ('Condo');
INSERT INTO a02PropertyType (propertyType) VALUES ('Semi-detached Home');
INSERT INTO a02PropertyType (propertyType) VALUES ('Single-garage detached Home');
INSERT INTO a02PropertyType (propertyType) VALUES ('Double-garage detached Home');
INSERT INTO a02PropertyType (propertyType) VALUES ('Manor Home');
INSERT INTO a02PropertyType (propertyType) VALUES ('Townhouse Complex');
INSERT INTO a02PropertyType (propertyType) VALUES ('Bungalow');
INSERT INTO a02PropertyType (propertyType) VALUES ('Cottage');
INSERT INTO a02PropertyType (propertyType) VALUES ('Vintage Home');

CREATE TABLE a02Location (
	propertyId NUMBER,
	streetAddress VARCHAR(30), 
	cityAddress VARCHAR(20),
	provinceAddress VARCHAR(15),
	postalCode VARCHAR(7),
	CONSTRAINT a02Location_PK PRIMARY KEY (propertyId)
);

INSERT INTO a02Location VALUES (122, '97 Boardwalk St.', 'Toronto', 'Ontario', 'L7R1Q6');
INSERT INTO a02Location VALUES (123, '29 Goldberry Sq.', 'Toronto', 'Ontario', 'L4F2E3');
INSERT INTO a02Location VALUES (124, '33 Riddleston Dr.', 'North York', 'Ontario', 'K9P0N5');
INSERT INTO a02Location VALUES (125, '4723 Moonlight Cres.', 'Richmond', 'British Columbia', 'B2D4T7');
INSERT INTO a02Location VALUES (126, '940 Swan Lake Rd.', 'Markham', 'Ontario', 'K0P1B4');
INSERT INTO a02Location VALUES (127, '2245 Grizzly Cir.', 'Etobicoke', 'Ontario', 'J4X2G2');
INSERT INTO a02Location VALUES (128, '314 Pekoe Pkwy', 'Brampton', 'Ontario', 'G8T4R6');
INSERT INTO a02Location VALUES (129, '8787 Rutherford Rd.', 'Mississauga', 'Ontario', 'M6T5Y7');
INSERT INTO a02Location VALUES (130, '839 Marvel Dr.', 'Brantford', 'Ontario', 'J9P4T2');
INSERT INTO a02Location VALUES (133, '38 Big Spoon Cres.', 'Milton', 'Ontario', 'V7T9F3');

CREATE TABLE a02Client (
	clientId NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, 
	firstName VARCHAR(20), 
	lastName VARCHAR(20), 
	mainContact# NUMBER, 
	emailAddress VARCHAR(35), 
	CONSTRAINT a02Client_PK PRIMARY KEY (clientId);
)

INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ('Nguyen', 'Wanda', 14165683546, 'wnguyen56@gmail.com');
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();
INSERT INTO a02Client (firstName, lastName, mainContact#, emailAddress) VALUES ();

CREATE TABLE a02PropertySOld (
	propertyId NUMBER,
	priceSold INTEGER,
	CONSTRAINT a02PropertySold_PK PRIMARY KEY (propertyId)
);

CREATE TABLE a02Condo (
	propertyId NUMBER,
	maintanenceFee INTEGER,
	CONSTRAINT a02Condo_PK PRIMARY KEY (propertyId)
);

CREATE TABLE a02House (
	propertyId NUMBER, 
	lotSize INTEGER
	CONSTRAINT a02House_PK PRIMARY KEY (propertyId)
);


CREATE TABLE a02PropertyInformation

CREATE TABLE a02Location

CREATE TABLE a02Area

